# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Bricks Animated 3D' do
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.5'
pod 'Google-Mobile-Ads-SDK', '~> 7.5'

end

